// Generate corpus/_reports/CORPUS.md from the shards and the state files.
//
//   node report.mjs
//
// Every number in the report is read out of the data at generation time. A
// hand-written corpus report is wrong the moment the next source finishes, and a
// wrong number in a document is worse than no document — this one is regenerated,
// not edited.
import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, resolve, basename } from 'node:path';
import { fileURLToPath } from 'node:url';
import { readShard } from './corpus_stats.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const CORPUS = resolve(HERE, '../../corpus');
const IN = resolve(CORPUS, 'recipes');

const readJson = async (p, fb) => {
  try {
    return JSON.parse(await readFile(p, 'utf8'));
  } catch {
    return fb;
  }
};

const pct = (n, d) => (d ? (n * 100 / d).toFixed(0) + '%' : '—');
const num = (n) => n.toLocaleString('en-US');

async function main() {
  const reg = await readJson(resolve(CORPUS, 'sources.json'), { sources: [] });
  const bySlug = new Map(reg.sources.map((s) => [s.slug, s]));

  let files = [];
  try {
    files = (await readdir(IN)).filter((f) => f.endsWith('.jsonl')).sort();
  } catch {
    console.log('no shards');
    return;
  }

  const t = {
    recipes: 0, ingredients: 0, steps: 0, chef: 0, image: 0, servings: 0, prep: 0,
    cook: 0, category: 0, cuisine: 0, keywords: 0, nutrition: 0, equipment: 0,
    stepGroups: 0, ingGroups: 0, metric: 0, video: 0, rating: 0, copycat: 0, mention: 0,
  };
  const byKind = new Map();
  const byCountry = new Map();
  const rows = [];
  const chefs = new Map();
  const chains = new Map();
  const cuisines = new Map();

  for (const f of files) {
    const slug = basename(f, '.jsonl');
    const src = bySlug.get(slug) || {};
    const row = { slug, name: src.name || slug, kind: src.kind || '?', n: 0, ing: 0, steps: 0, chefs: new Set() };
    for await (const r of readShard(resolve(IN, f))) {
      row.n++;
      t.recipes++;
      const ing = r.ingredientGroups.reduce((a, g) => a + g.items.length, 0);
      row.ing += ing;
      row.steps += r.steps.length;
      t.ingredients += ing;
      t.steps += r.steps.length;
      const a = r.attribution || {};
      if (a.chef) {
        t.chef++;
        row.chefs.add(a.chef);
        chefs.set(a.chef, (chefs.get(a.chef) || 0) + 1);
      }
      if (a.isCopycat) t.copycat++;
      for (const m of a.restaurantMentioned || []) {
        t.mention++;
        chains.set(m.name, (chains.get(m.name) || 0) + 1);
      }
      if (r.media && r.media.coverImages && r.media.coverImages.length) t.image++;
      if (r.media && r.media.video) t.video++;
      if (r.yield && r.yield.servings != null) t.servings++;
      if (r.timing && r.timing.prepMinutes != null) t.prep++;
      if (r.timing && r.timing.cookMinutes != null) t.cook++;
      if (r.category && r.category.length) t.category++;
      if (r.cuisine && r.cuisine.length) {
        t.cuisine++;
        for (const c of r.cuisine) cuisines.set(c, (cuisines.get(c) || 0) + 1);
      }
      if (r.keywords && r.keywords.length) t.keywords++;
      if (r.nutrition && Object.keys(r.nutrition).length) t.nutrition++;
      if (r.equipment && r.equipment.length) t.equipment++;
      if (r.steps.some((s) => s.stepGroup)) t.stepGroups++;
      if (r.ingredientGroups.length > 1 || r.ingredientGroups.some((g) => g.name)) t.ingGroups++;
      if (r.ingredientGroups.some((g) => g.items.some((i) => i.metric))) t.metric++;
      if (r.unmappedFields && r.unmappedFields.aggregateRating) t.rating++;
    }
    if (!row.n) continue;
    rows.push(row);
    byKind.set(row.kind, (byKind.get(row.kind) || 0) + row.n);
    const c = src.country || 'unstated';
    byCountry.set(c, (byCountry.get(c) || 0) + row.n);
  }

  // Failure tallies come from the resume state, not the shards: a page that was
  // rejected leaves no record in the data by design.
  const failures = new Map();
  let attempted = 0;
  let discovered = 0;
  for (const s of reg.sources) {
    const st = await readJson(resolve(CORPUS, '_state', s.slug + '.json'), null);
    if (!st) continue;
    attempted += (st.done || []).length;
    for (const [k, v] of Object.entries(st.failed || {})) failures.set(k, (failures.get(k) || 0) + v);
    const d = await readJson(resolve(CORPUS, '_state/discovered', s.slug + '.json'), null);
    if (d) discovered += d.urls.length;
  }

  rows.sort((a, b) => b.n - a.n);
  const top = (m, n) => [...m.entries()].sort((a, b) => b[1] - a[1]).slice(0, n);

  const disabled = reg.sources.filter((s) => s.enabled === false);

  const md = [];
  md.push('# The scraped recipe corpus');
  md.push('');
  md.push('Generated by `recipeData/_tools/report.mjs` — do not edit; re-run it.');
  md.push('');
  md.push('Generated ' + new Date().toISOString().slice(0, 16).replace('T', ' ') + ' UTC.');
  md.push('');
  md.push('## Totals');
  md.push('');
  md.push('| | |');
  md.push('|---|---|');
  md.push('| Recipes | **' + num(t.recipes) + '** |');
  md.push('| Ingredient lines | ' + num(t.ingredients) + ' |');
  md.push('| Steps | ' + num(t.steps) + ' |');
  md.push('| Sources producing | ' + rows.length + ' of ' + reg.sources.length + ' registered |');
  md.push('| Distinct named chefs | ' + num(chefs.size) + ' |');
  md.push('| Restaurant/chain mentions | ' + num(t.mention) + ' across ' + chains.size + ' chains |');
  md.push('| Pages fetched | ' + num(attempted) + ' of ' + num(discovered) + ' discovered |');
  md.push('| Mean ingredients per recipe | ' + (t.recipes ? (t.ingredients / t.recipes).toFixed(1) : '0') + ' |');
  md.push('| Mean steps per recipe | ' + (t.recipes ? (t.steps / t.recipes).toFixed(1) : '0') + ' |');
  md.push('');
  md.push('## By kind of publisher');
  md.push('');
  md.push('| Kind | Recipes | Share |');
  md.push('|---|---:|---:|');
  for (const [k, v] of [...byKind.entries()].sort((a, b) => b[1] - a[1])) {
    md.push('| ' + k + ' | ' + num(v) + ' | ' + pct(v, t.recipes) + ' |');
  }
  md.push('');
  md.push('## Field coverage');
  md.push('');
  md.push('What the web actually publishes, measured rather than assumed. The right-hand');
  md.push('column is the share of captured recipes carrying the field at all.');
  md.push('');
  md.push('| Field | Recipes | Share |');
  md.push('|---|---:|---:|');
  const cov = [
    ['named chef', t.chef], ['cover image', t.image], ['keywords / tags', t.keywords],
    ['servings (integer)', t.servings], ['prep time', t.prep], ['cook time', t.cook],
    ['category', t.category], ['cuisine', t.cuisine], ['nutrition block', t.nutrition],
    ['grouped ingredients', t.ingGroups], ['step sections', t.stepGroups],
    ['equipment', t.equipment], ['metric weight in parens', t.metric],
    ['video', t.video], ['aggregateRating', t.rating],
    ['framed as copycat', t.copycat],
  ];
  for (const [label, n] of cov) md.push('| ' + label + ' | ' + num(n) + ' | ' + pct(n, t.recipes) + ' |');
  md.push('');
  md.push('## What this corpus can test that batch 1 could not');
  md.push('');
  md.push('Phase 1 captured 108 recipes from one publisher and reported four app gaps as');
  md.push('**unexercised**, because BBC Food publishes none of them: step sections, equipment,');
  md.push('structured step durations and step temperatures. At this scale three of the four');
  md.push('have real data behind them, which turns each from a hypothesis into a decision');
  md.push('with a count against it.');
  md.push('');
  md.push('| Concept | Batch 1 (108 recipes) | Now | App support |');
  md.push('|---|---:|---:|---|');
  md.push('| step sections | 0 | ' + num(t.stepGroups) + ' | modelled (`step_groups`) — and now genuinely tested |');
  md.push('| equipment / utensils | 0 | ' + num(t.equipment) + ' | **no column at all** |');
  md.push('| grouped ingredients | 73 | ' + num(t.ingGroups) + ' | modelled (`ingredient_groups`) |');
  md.push('| nutrition block | 10 | ' + num(t.nutrition) + ' | modelled (`recipes.nutrition`) |');
  md.push('| video | 15 | ' + num(t.video) + ' | no column |');
  md.push('| keywords / tags | 108 | ' + num(t.keywords) + ' | tables exist, **no app code touches them** |');
  md.push('');
  md.push('## Largest sources');
  md.push('');
  md.push('| Source | Kind | Recipes | Named chefs |');
  md.push('|---|---|---:|---:|');
  for (const r of rows.slice(0, 25)) {
    md.push('| ' + r.name + ' | ' + r.kind + ' | ' + num(r.n) + ' | ' + r.chefs.size + ' |');
  }
  md.push('');
  md.push('## Most-represented chefs');
  md.push('');
  md.push('| Chef | Recipes |');
  md.push('|---|---:|');
  for (const [name, n] of top(chefs, 20)) md.push('| ' + name + ' | ' + num(n) + ' |');
  md.push('');
  md.push('## Restaurants and chains named by a recipe');
  md.push('');
  md.push('A **mention**, never the publisher: a copycat recipe is published by the blogger,');
  md.push('not by the chain. See `brands.mjs`.');
  md.push('');
  md.push('| Chain | Recipes naming it |');
  md.push('|---|---:|');
  for (const [name, n] of top(chains, 20)) md.push('| ' + name + ' | ' + num(n) + ' |');
  md.push('');
  md.push('## Cuisines declared');
  md.push('');
  md.push(top(cuisines, 25).map(([c, n]) => c + ' (' + n + ')').join(', ') || '—');
  md.push('');
  md.push('## What was fetched and not kept');
  md.push('');
  md.push('| Reason | Pages |');
  md.push('|---|---:|');
  for (const [k, v] of [...failures.entries()].sort((a, b) => b[1] - a[1])) {
    md.push('| `' + k + '` | ' + num(v) + ' |');
  }
  md.push('');
  md.push('`no-recipe-jsonld` is overwhelmingly a genuine non-recipe post — a round-up, a');
  md.push('meal plan, an essay — sitting in the same sitemap as the recipes. Sampling the');
  md.push('rejects confirmed it: the pages have no recipe markup of any kind, so a microdata');
  md.push('fallback would not recover them.');
  md.push('');
  if (disabled.length) {
    md.push('## Sources switched off');
    md.push('');
    md.push('| Source | Reason |');
    md.push('|---|---|');
    for (const s of disabled) md.push('| ' + (s.name || s.slug) + ' | ' + (s.disabledReason || 'by hand') + ' |');
    md.push('');
  }
  md.push('## Rights');
  md.push('');
  md.push('Recipe text belongs to its rights-holder. Each record stores functional content —');
  md.push('ingredients, quantities, steps — plus the source URL and the publisher, so the');
  md.push('credit travels with the row. This corpus is for internal development and testing');
  md.push('only: not for redistribution, not training data, and never promoted into');
  md.push('`supabase/seed*.sql`.');
  md.push('');

  const out = resolve(CORPUS, '_reports/CORPUS.md');
  await mkdir(dirname(out), { recursive: true });
  await writeFile(out, md.join('\n'), 'utf8');
  console.log('wrote ' + out + '  (' + num(t.recipes) + ' recipes, ' + rows.length + ' sources)');
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
