// tool/db.dart — thin cross-platform wrapper around `psql` for DB tasks.
//
// Usage (via melos):
//   melos run db:create | db:seed | db:recipes | db:drop | db:clean | db:reset
//   melos run db:sim | db:sim:verify | db:sim:rls | db:sim:clean
//   melos run db:audit | db:purge:fake
//   melos run db:rls
//   melos run db:hosted:check | db:hosted:deploy
// Requires:
//   * `psql` on PATH (PostgreSQL client) — OR `--docker`, which runs the client
//     inside `postgres:17-alpine` instead. On this machine there is no local
//     client at all (B033), so `--docker` is the working form for everything,
//     and it is the correct form for anything hosted regardless (B079).
//   * SUPABASE_DB_URL env var — the connection string from the Supabase
//     dashboard (Project Settings -> Database -> Connection string -> URI).
//
// Example (PowerShell):
//   $env:SUPABASE_DB_URL = "postgresql://postgres:<pwd>@db.<ref>.supabase.co:5432/postgres"
//   melos run db:reset
//
// No `psql` installed? The Supabase CLI's local DB container ships one — see
// README.md, and docs/BUG-TRACKER.md B033 for the hosted-project form.

import 'dart:io';

/// Steps that apply **every** `.sql` file in a directory, in filename order.
///
/// `create` is one of these as of OPT-A9: `supabase/migrations/` is a numbered
/// sequence now, not a single file that gets edited forever. `0001_init.sql`
/// stays the idempotent baseline — it is what a fresh database is built from —
/// and every schema change after it is a **new** numbered file. See
/// `supabase/migrations/README.md` for the rules that keeps honest.
const _directories = <String, String>{
  'create': 'supabase/migrations',
  // The captured corpus (Phase 35c), 500 recipes per shard. GENERATED and
  // git-ignored — run `melos run corpus:import:gen` first, which is the step
  // that reads 8.6 GB of scraped data; this one only applies the SQL it wrote,
  // so the tool that touches the corpus never holds a database credential
  // (Gotcha 7). Idempotent: `unique(source_entity_id, source_url)` means a
  // re-apply inserts nothing, which is what makes it safe to re-run after a
  // partial failure. Deliberately NOT part of `reset` — a reset is the 14
  // curated recipes, and pulling 21k rows over a pooler is a minutes-long
  // operation nobody wants inside a loop they run all day.
  'corpus': 'corpus/_import',
};

/// Single-file steps, by name.
const _files = <String, String>{
  'seed': 'supabase/seed.sql',
  // Generated from recipeData/recipes/*.json by tool/recipes.dart. Standalone
  // and order-independent with respect to `seed`: both bootstrap the same
  // Secret Sauce Kitchen account with conflict guards.
  'recipes': 'supabase/seed_recipes.sql',
  // Generated from nutritionData/ by tool/nutrition.dart. Reference data, not
  // demo data: `clean` leaves it alone. Ordered BEFORE `recipes` in `reset`
  // because Phase 29b gives ingredients a food_id FK into it.
  'nutrition': 'supabase/nutrition_foods.sql',
  'drop': 'supabase/scripts/drop.sql',
  'clean': 'supabase/scripts/clean.sql',
  // Simulation (docs/ROADMAP.md Phase 24). Split by lifecycle, not by taste:
  // the schema and the dish library are cheap and reusable, the generator is
  // the expensive part, and the teardown is destructive.
  'sim:schema': 'supabase/sim/0_sim_schema.sql',
  // The three authored pools, all generated by tool/sim.dart from simData/ and
  // all `1_`-numbered because they are peers: the generator needs every one of
  // them before it draws anything. `sim:dishes` supplies the recipes,
  // `sim:people` the names and bios, `sim:vocab` the tag ranks and the title
  // templates — and the last of those is load-bearing rather than decorative,
  // because a recipe's title comes from `sim.title_variant` and an empty pool
  // generates NO recipes at all.
  'sim:dishes': 'supabase/sim/1_sim_dishes.sql',
  'sim:people': 'supabase/sim/1_sim_people.sql',
  'sim:vocab': 'supabase/sim/1_sim_vocab.sql',
  'sim:generate': 'supabase/sim/2_sim_generate.sql',
  'sim:verify': 'supabase/sim/3_sim_verify.sql',
  // The per-persona RLS smoke (Phase 24's last open verification item). Seats
  // one REAL actor per persona from the `sim.actor` registry and re-runs the
  // policy claims as that signed-in user — the case neither 3_sim_verify (which
  // runs as `postgres` and so bypasses every policy) nor rls_matrix (which
  // builds its own three-user fixture) covers. Deliberately NOT in the `sim`
  // pipeline below: it WRITES before it rolls back, and `sim` runs inside
  // `reset`. Exempt from `-1` for the same reason `rls` is — its `rollback`
  // *is* the cleanup.
  'sim:rls': 'supabase/sim/4_sim_rls_smoke.sql',
  'sim:teardown': 'supabase/sim/9_sim_teardown.sql',
  // The RLS acceptance matrix (docs/ROADMAP.md BL-7). Creates three throwaway
  // users and two recipes, re-runs the whole authorization matrix as each of
  // them under `set local role authenticated`, and ROLLS THE WHOLE THING BACK.
  // Exempt from `-1` below because it owns that transaction itself.
  'rls': 'supabase/tests/rls_matrix.sql',
  // The auto-nutrition arithmetic on fixture trees (Phase 29c) and the
  // committed labels against the committed registry (Phase 29d). Both own
  // their transaction and roll it back, so both are `-1`-exempt for the same
  // reason `rls` is. `nutrition:estimate` is self-sufficient; `nutrition:verify`
  // needs the registry AND the recipes already applied. Note the neighbouring
  // melos script `nutrition:check` is a different thing — a pure file staleness
  // check on the generated SQL, no database involved.
  'nutrition:estimate': 'supabase/tests/nutrition_estimate.sql',
  'nutrition:verify': 'supabase/tests/nutrition_fixtures.sql',
  // Classify every profile, recipe and account as real or fabricated
  // (B112/B113/B114). READ-ONLY — creates temporary tables and nothing else —
  // so it is safe against the hosted project and is the last step of `reset`.
  // `--strict` makes a finding an error, which is how CI proves that a default
  // apply path cannot produce fabricated rows.
  'audit': 'supabase/tests/data_audit.sql',
  // A sorted catalogue inventory of the `public` schema — tables, columns,
  // enums, function signatures, RLS, policies, grants, indexes, triggers and
  // constraints. READ-ONLY, and the basis of `db:hosted:check`: the hosted
  // project has no `supabase_migrations.schema_migrations` row to compare a
  // version against (it was applied by hand), so the only honest way to ask
  // whether it still matches the repo is to inventory both and diff.
  'fingerprint': 'supabase/scripts/schema_fingerprint.sql',
  // The destructive counterpart. Removes seed.sql's fixed-id demo fixtures and
  // ingest.mjs's impersonation accounts, then repairs authored counters. The
  // simulated population is NOT handled here — `purge:fake` runs the sim's own
  // registry-driven teardown first, so there is only ever one copy of that
  // logic (see the pipeline below).
  'purge:fake:rows': 'supabase/scripts/purge_fake.sql',
};

/// Multi-step actions, in order.
const _pipelines = <String, List<String>>{
  // `seed` and `sim` are DELIBERATELY ABSENT (B113). Both fabricate data — 15
  // demo accounts with authored counters, and a 250-account simulated
  // population — and having them in the default reset meant every developer
  // database, and the hosted project, showed invented chefs on the leaderboard
  // as though they were users. They are now test-only: CI builds them in its
  // throwaway Postgres, and `melos run db:seed` / `db:sim` still run them
  // on demand for someone who wants a populated board to look at.
  //
  // What a reset produces now is exactly the real content: the schema, the food
  // registry, and the 14 curated recipes under the first-party Secret Sauce
  // Kitchen account, all with zero engagement. `audit` runs last and is the
  // proof — it fails if any step above it fabricated a row.
  'reset': ['drop', 'create', 'nutrition', 'recipes', 'audit'],
  'sim': [
    'sim:schema',
    'sim:dishes',
    'sim:people',
    'sim:vocab',
    'sim:generate',
    'sim:verify',
  ],
  'sim:clean': ['sim:teardown'],
  // Order matters and the split is the point: the simulated population already
  // has a reviewed, registry-driven teardown, so `purge:fake` reuses it rather
  // than growing a second copy of that logic. `purge:fake:rows` then handles
  // what it does not cover — the fixed-id demo fixtures, the impersonation
  // accounts, and the authored-counter repair — and `audit` proves the result.
  'purge:fake': ['sim:teardown', 'purge:fake:rows', 'audit'],
  // Bring a database that is not this machine's local stack up to the repo:
  // schema, food registry, the 14 curated recipes, the captured corpus, then
  // the audit as proof. Every step is idempotent, so this is also the re-run
  // after a partial failure and the routine way to push a schema change.
  //
  // It is NOT a reset and deliberately contains no `drop`: the whole point is
  // that it can be pointed at a database holding real accounts and real
  // recipes. `0001_init.sql` upgrades in place (Gotcha 5), `seed_recipe_v2`
  // returns early on a recipe that already exists, and the corpus shards are
  // keyed `unique(source_entity_id, source_url)`.
  //
  // `audit` runs last and in `--strict` mode via the hook below, so a deploy
  // that somehow fabricated a row fails instead of reporting success.
  'hosted:deploy': ['create', 'nutrition', 'recipes', 'corpus', 'audit'],
};

/// Actions that destroy data and therefore require an explicit `--yes`.
const _destructive = {'sim:clean', 'purge:fake', 'purge:fake:rows'};

/// Actions that write a lot to a database that is probably not this machine's,
/// and therefore also require `--yes` — with a different reason than
/// [_destructive], so they get their own message rather than being told they
/// delete `auth.users` rows, which they do not.
///
/// Nothing here is reversible in the sense that matters: the free tier has no
/// PITR, so the undo for a bad deploy is the dump `db:backup` took beforehand.
const _needsConfirmation = {'hosted:deploy'};

/// The two dumps a restorable backup needs (B087, Phase 32f5).
///
/// **`--schema=public` alone is not a backup of this project.** Every
/// `profiles.id` is an FK to `auth.users`, so a public-only dump restores into a
/// project whose accounts do not exist: the restore itself fails on the FK, and
/// if it did not, the result would be a vault of recipes nobody can sign in to
/// own. The free tier has no PITR, so this pair is production's only undo.
///
/// Auth is dumped **data-only and table-by-table**, never `--schema=auth`: a
/// fresh Supabase project already owns that schema (as `supabase_auth_admin`,
/// with its own version of the tables), so restoring auth DDL collides on
/// ownership before it reaches a single row.
///
/// What is **not** covered, stated rather than implied: Storage objects. The
/// `storage.objects` rows ride in neither dump and the bytes live in S3, so a
/// restore comes back with recipes whose `cover_image_url` points at nothing.
const _dumps = <({String name, List<String> args})>[
  (name: 'public', args: ['--schema=public', '--no-owner', '--no-privileges']),
  (
    name: 'auth',
    args: ['--data-only', '--table=auth.users', '--table=auth.identities'],
  ),
];

/// Steps applied inside a **single transaction** (`psql -1`), so a failure
/// halfway through a file rolls the whole file back (OPT-T6).
///
/// `ON_ERROR_STOP=1` already stops the run at the first error, but without `-1`
/// everything before it has committed: a schema apply that dies two thirds of
/// the way through leaves two thirds of a schema, and the next run starts from
/// a state nothing describes.
///
/// The sim files are **exempt** and must stay that way — they open and close
/// their own transactions around the bulk load (and toggle triggers on the
/// tables they write), which `-1` would nest and break. `rls` is exempt for the
/// same reason and a sharper one: its `rollback` *is* the cleanup.
const _transactional = {
  'create',
  'seed',
  'recipes',
  'nutrition',
  'drop',
  'clean',
  // One transaction per corpus shard, matching the `-1` in the hand-run form
  // CLAUDE.md documents. The shards carry no transaction control of their own
  // (they are flat `select import_recipe(...)` lists), and B110 is the reason
  // this matters: one malformed scraped page aborts its batch, and without `-1`
  // the 300 rows ahead of it have already committed. The import is idempotent,
  // so a re-run would finish the job either way — but "the next run starts from
  // a state nothing describes" is the exact thing OPT-T6 added `-1` to prevent.
  'corpus',
};

/// Whether every `psql` invocation runs inside `postgres:17-alpine` rather than
/// using a client from PATH. Set once by the global `--docker` flag.
///
/// This is not a convenience flag (B033). On a Windows machine with no
/// PostgreSQL client installed, the only `psql` available is the one inside the
/// local Supabase stack's container — and that one is **15.8** while the hosted
/// project runs **17.6**. `psql` tolerates that gap where `pg_dump` does not, so
/// the stack's client appears to work right up until the day you need a backup
/// (B079). Running the client from a pinned image whose major matches the server
/// makes every `db:*` action behave the same from PowerShell and from Bash, with
/// no shell in the path to re-encode a multibyte character (B074).
bool _useDockerPsql = false;

/// The repo root, mounted read-only at `/repo` inside the container so that the
/// repo-relative `-f` paths in [_files] and [_directories] resolve unchanged.
final String _repoRoot = Directory.current.absolute.path;

Future<int> _psql(
  String url,
  List<String> args, {
  bool singleTransaction = false,
}) async {
  final psqlArgs = <String>[
    '-v',
    'ON_ERROR_STOP=1',
    if (singleTransaction) '-1',
    ...args,
  ];

  if (!_useDockerPsql) {
    final proc = await Process.start('psql', [
      url,
      ...psqlArgs,
    ], mode: ProcessStartMode.inheritStdio);
    return proc.exitCode;
  }

  // Inside a container `127.0.0.1` is the container itself, so a loopback URL
  // has to be pointed back at the host; a hosted URL is left alone, which is
  // the case this form exists for.
  final target = _dockerReachable(url);
  final proc = await Process.start('docker', [
    'run',
    '--rm',
    '-i',
    if (target != url) '--add-host=host.docker.internal:host-gateway',
    // Read-only: this mount carries the SQL in, never anything out.
    '-v',
    '$_repoRoot:/repo:ro',
    '-w',
    '/repo',
    'postgres:17-alpine',
    'psql',
    target,
    ..._containerPaths(psqlArgs),
  ], mode: ProcessStartMode.inheritStdio);
  return proc.exitCode;
}

/// [args] with every `-f` operand rewritten to its path inside the container.
///
/// Paths in [_files] / [_directories] are repo-relative and may arrive with
/// Windows separators, which `psql` inside a Linux container cannot open.
List<String> _containerPaths(List<String> args) {
  final out = <String>[];
  for (var i = 0; i < args.length; i++) {
    out.add(args[i]);
    if (args[i] == '-f' && i + 1 < args.length) {
      out.add('/repo/${args[i + 1].replaceAll(r'\', '/')}');
      i++;
    }
  }
  return out;
}

Future<int> _applyFile(
  String url,
  String step, {
  Map<String, String> vars = const {},
}) async {
  final dir = _directories[step];
  if (dir != null) return _applyDirectory(url, step, dir);

  final path = _files[step]!;
  if (!File(path).existsSync()) {
    stderr.writeln('Missing SQL file: $path');
    return 1;
  }
  stdout.writeln('▶ $step  ($path)');
  return _psql(url, [
    for (final entry in vars.entries) ...['-v', '${entry.key}=${entry.value}'],
    '-f',
    path,
  ], singleTransaction: _transactional.contains(step));
}

/// psql `-v` variables a given step needs, derived from the command-line flags.
///
/// Both consumers default themselves when the variable is absent
/// (`\if :{?strict}` / `\if :{?confirm}`), so passing nothing is a valid state
/// and a hand-run `psql -f` behaves the same as this wrapper — the same
/// principle as the sim reading its knobs from `sim.config`.
Map<String, String> _stepVars(
  String step, {
  required bool confirmed,
  required bool strict,
}) => switch (step) {
  // Reports by default and only FAILS under `--strict`, because `db:audit` is
  // the command someone runs to find out what is in a database — including
  // right after `db:sim`, which fabricates a population on purpose. An
  // informational command that exits non-zero for doing its job gets ignored.
  //
  // `reset` forces strict on (see main): there the claim being made is that a
  // default apply path CANNOT fabricate a row, and a claim that only prints is
  // not a gate.
  'audit' => {'strict': strict ? 'on' : 'off'},
  'purge:fake:rows' => {'confirm': confirmed ? 'yes' : 'no'},
  _ => const {},
};

/// Applies every `.sql` file in [dir], sorted by name — the same order the
/// Supabase CLI uses, so `melos run db:create` and `supabase db reset` cannot
/// disagree about what "the schema" is.
///
/// It applies **all** of them, including ones this database has already seen:
/// nothing here tracks migration history (the CLI's `schema_migrations` table
/// does that for `supabase db reset` / `db push`). That is why every migration
/// has to stay idempotent — see `supabase/migrations/README.md`. On a hosted
/// database with real data, prefer applying only the new file: re-running the
/// baseline is safe but re-runs its backfills, which is the cost OPT-A9 exists
/// to stop paying on every change.
Future<int> _applyDirectory(String url, String step, String dir) async {
  final directory = Directory(dir);
  if (!directory.existsSync()) {
    stderr.writeln('Missing SQL directory: $dir');
    return 1;
  }
  // Sorted by full path, which sorts by filename here because the directory
  // prefix is identical — that is what makes `0002_` follow `0001_`, and why
  // migrations are numbered rather than named.
  final files =
      directory
          .listSync()
          .whereType<File>()
          .where((f) => f.path.toLowerCase().endsWith('.sql'))
          .map((f) => f.path)
          .toList()
        ..sort();

  if (files.isEmpty) {
    stderr.writeln('No .sql files in $dir');
    return 1;
  }

  // One transaction **per file**, not one across the directory: a migration is
  // the unit that has to be all-or-nothing, and 0002 failing must not undo 0001
  // on a database that had never seen either.
  for (final path in files) {
    stdout.writeln('▶ $step  ($path)');
    final code = await _psql(url, [
      '-f',
      path,
    ], singleTransaction: _transactional.contains(step));
    if (code != 0) return code;
  }
  return 0;
}

/// Writes the run's knobs into `sim.config` before the generator reads them.
/// The SQL deliberately reads its configuration from a table rather than from
/// psql `-v` variables, so that a hand-run file behaves the same as this
/// wrapper does.
Future<int> _configureSim(String url, String? preset, int? seed) async {
  final sets = <String>[
    if (preset != null) "('preset', '$preset')",
    if (seed != null) "('seed', '$seed')",
  ];
  if (sets.isEmpty) return 0;
  stdout.writeln('▶ sim:config  (${sets.join(', ')})');
  return _psql(url, [
    '-c',
    'insert into sim.config (key, value) values ${sets.join(', ')} '
        'on conflict (key) do update set value = excluded.value',
  ]);
}

/// Dumps [_dumps] into [outDir], timestamped, and returns 0 on success.
///
/// [stamp] is passed in rather than read here so the two files of one run share
/// a name, and [useDocker] runs the dump inside `postgres:17-alpine` instead of
/// from PATH. That is not a convenience: `pg_dump` **aborts on a server major
/// newer than its own**, the hosted project runs 17.x, and the client inside the
/// local Supabase stack is 15.8 (B079) — so on a machine whose only client is
/// the stack's, the container is the only form that can back up production at
/// all. `psql` tolerates that gap, which is exactly why the mismatch goes
/// unnoticed until the day it matters.
Future<int> _backup(
  String url,
  String outDir,
  String stamp, {
  required bool useDocker,
}) async {
  final dir = Directory(outDir);
  if (!dir.existsSync()) dir.createSync(recursive: true);
  final absolute = dir.absolute.path;

  // Inside a container, `127.0.0.1` is the container. A loopback URL therefore
  // has to be rewritten to reach the host's stack, and the gateway alias has to
  // be added because it is not automatic outside Docker Desktop. Hosted URLs
  // are untouched — they are the case this form exists for.
  final target = useDocker ? _dockerReachable(url) : url;
  final hostAlias =
      useDocker && target != url
          ? ['--add-host=host.docker.internal:host-gateway']
          : const <String>[];

  for (final dump in _dumps) {
    final file = '${dump.name}_$stamp.sql';
    stdout.writeln('▶ backup  ($outDir/$file)');
    final Process proc;
    if (useDocker) {
      proc = await Process.start('docker', [
        'run',
        '--rm',
        ...hostAlias,
        // The output directory is mounted rather than streamed, so the bytes
        // never pass through a shell that could re-encode them (B074).
        '-v',
        '$absolute:/backup',
        'postgres:17-alpine',
        'pg_dump',
        target,
        ...dump.args,
        '-f',
        '/backup/$file',
      ], mode: ProcessStartMode.inheritStdio);
    } else {
      proc = await Process.start('pg_dump', [
        url,
        ...dump.args,
        '-f',
        '$outDir/$file',
      ], mode: ProcessStartMode.inheritStdio);
    }
    final code = await proc.exitCode;
    if (code != 0) return code;
  }

  stdout.writeln(
    'Restore order is auth BEFORE public — the FKs point that way.\n'
    'Storage objects are NOT in these files; see README.md#backups.',
  );
  return 0;
}

/// [url] with a loopback host swapped for `host.docker.internal`, unchanged
/// otherwise. Returns the input on an unparseable string rather than guessing.
String _dockerReachable(String url) {
  try {
    final uri = Uri.parse(url);
    if (uri.host != '127.0.0.1' && uri.host != 'localhost') return url;
    return uri.replace(host: 'host.docker.internal').toString();
  } on FormatException {
    return url;
  }
}

/// The host being targeted, with any credential stripped. `db:*` fires at
/// whatever SUPABASE_DB_URL points at with no prod guard (CLAUDE.md Gotcha 7),
/// so the least this can do is say where.
String _describeTarget(String url) {
  try {
    final uri = Uri.parse(url);
    return '${uri.host}:${uri.port}${uri.path}';
  } on FormatException {
    return '(unparseable connection string)';
  }
}

void _usage() {
  stdout.writeln('''
usage: dart run tool/db.dart <action> [options]

  create                                   apply every supabase/migrations/*.sql, in order
  seed | recipes | nutrition | drop | clean  apply one SQL file
  reset                                    drop -> create -> nutrition -> seed -> recipes -> sim
  sim                                      schema -> pools (dishes, people, vocab)
                                           -> generate -> verify
  sim:verify                               assertions only, read-only
  sim:rls                                  the RLS policies per persona, as a signed-in
                                           actor from sim.actor (rolls back)
  sim:clean                                DESTRUCTIVE teardown (requires --yes)
  audit                                    classify every row as real or fabricated (read-only)
  purge:fake                               DESTRUCTIVE sim teardown + fixture/impersonation
                                           purge + audit (requires --yes)
  rls                                      the RLS matrix as a signed-in user (rolls back)
  nutrition:estimate                       estimator arithmetic on fixture trees (rolls back)
  nutrition:verify                         committed labels vs. the registry (rolls back)
  corpus                                   apply corpus/_import/*.sql (idempotent; run
                                           `melos run corpus:import:gen` first)
  fingerprint                              inventory the public schema (read-only) — the
                                           basis of the hosted drift check
  hosted:deploy                            create -> nutrition -> recipes -> corpus ->
                                           audit --strict. Additive, idempotent, no drop.
                                           Requires --yes
  backup                                   pg_dump public + auth data, timestamped (read-only)

options:
  --preset=<tiny|small|medium|large>       sim size (default: whatever sim.config holds)
  --seed=<int>                             sim random seed
  --out=<dir>                              backup destination (default: backups/)
  --docker                                 run psql AND pg_dump in postgres:17-alpine.
                                           Required on a machine with no PostgreSQL
                                           client installed (B033), and the right form
                                           for anything hosted (B079)
  --strict                                 audit: exit non-zero on any finding
                                           (implied by `reset`)
  --yes                                    confirm a destructive action
''');
}

Future<void> main(List<String> args) async {
  final url = Platform.environment['SUPABASE_DB_URL'];
  if (url == null || url.isEmpty) {
    stderr.writeln(
      'SUPABASE_DB_URL is not set.\n'
      'Get it from Supabase -> Project Settings -> Database -> Connection string (URI),\n'
      'then e.g.  \$env:SUPABASE_DB_URL = "postgresql://postgres:<pwd>@db.<ref>.supabase.co:5432/postgres"',
    );
    exit(2);
  }

  final positional = args.where((a) => !a.startsWith('--')).toList();
  final flags = args.where((a) => a.startsWith('--')).toList();
  final action = positional.isEmpty ? 'help' : positional.first;

  String? optionOf(String name) {
    final hit = flags.where((f) => f.startsWith('--$name=')).toList();
    return hit.isEmpty ? null : hit.first.substring(name.length + 3);
  }

  final preset = optionOf('preset');
  final seedOpt = optionOf('seed');
  final outDir = optionOf('out') ?? 'backups';
  final confirmed = flags.contains('--yes');

  // Applies to every step, not just `backup`: with no PostgreSQL client on
  // PATH this is the only way `db:*` runs at all on this machine (B033), and
  // against hosted it is the form that keeps the client major matched to the
  // server (B079).
  _useDockerPsql = flags.contains('--docker');

  if (seedOpt != null && int.tryParse(seedOpt) == null) {
    stderr.writeln('--seed must be an integer (got "$seedOpt")');
    exit(64);
  }
  const presets = {'tiny', 'small', 'medium', 'large'};
  if (preset != null && !presets.contains(preset)) {
    stderr.writeln(
      '--preset must be one of ${presets.join(', ')} (got "$preset")',
    );
    exit(64);
  }

  // Read-only and file-producing rather than file-applying, so it short-circuits
  // the step machinery below entirely.
  if (action == 'backup') {
    stdout.writeln('target: ${_describeTarget(url)}');
    final now = DateTime.now().toUtc();
    String two(int v) => v.toString().padLeft(2, '0');
    final stamp =
        '${now.year}${two(now.month)}${two(now.day)}'
        'T${two(now.hour)}${two(now.minute)}${two(now.second)}Z';
    final code = await _backup(
      url,
      outDir,
      stamp,
      useDocker: flags.contains('--docker'),
    );
    if (code != 0) {
      stderr.writeln(
        '✖ backup failed (exit $code).\n'
        '  No pg_dump on PATH? Re-run with --docker, which uses '
        'postgres:17-alpine —\n'
        '  and note a client older than the server aborts outright (B079).',
      );
      exit(code);
    }
    stdout.writeln('✔ done');
    return;
  }

  final steps =
      _pipelines[action] ??
      ((_files.containsKey(action) || _directories.containsKey(action))
          ? [action]
          : const <String>[]);

  if (action == 'help' || steps.isEmpty) {
    _usage();
    exit(action == 'help' ? 0 : 64);
  }

  if (_destructive.contains(action) && !confirmed) {
    stderr.writeln(
      '✖ $action deletes rows from auth.users on ${_describeTarget(url)}.\n'
      '  auth.users has no undo. Re-run with --yes to confirm.',
    );
    exit(3);
  }

  if (_needsConfirmation.contains(action) && !confirmed) {
    stderr.writeln(
      '✖ $action writes the schema, the food registry, the curated recipes and\n'
      '  the whole captured corpus to ${_describeTarget(url)}.\n'
      '  Take a backup first (`db:backup -- --docker --out=<dir>`); the free\n'
      '  tier has no PITR, so that dump is the only undo.\n'
      '  Re-run with --yes to confirm.',
    );
    exit(3);
  }

  stdout.writeln('target: ${_describeTarget(url)}');

  // Flatten first: a pipeline entry may itself be a pipeline (`reset` contains
  // `sim`), and the sim:generate hook below has to see the real leaf rather
  // than the group that contains it.
  final leaves = <String>[
    for (final step in steps) ...(_pipelines[step] ?? [step]),
  ];

  for (final leaf in leaves) {
    // The generator reads its knobs from sim.config, so they have to be written
    // after the schema exists and before the generator runs.
    if (leaf == 'sim:generate') {
      final code = await _configureSim(
        url,
        preset,
        seedOpt == null ? null : int.parse(seedOpt),
      );
      if (code != 0) {
        stderr.writeln('✖ sim:config failed (exit $code)');
        exit(code);
      }
    }
    final code = await _applyFile(
      url,
      leaf,
      vars: _stepVars(
        leaf,
        confirmed: confirmed,
        // `reset` and `hosted:deploy` assert rather than report: the contract
        // of both is that what they produce contains nothing fabricated, and
        // for the second of those the database on the other end is production.
        strict:
            flags.contains('--strict') ||
            action == 'reset' ||
            action == 'hosted:deploy',
      ),
    );
    if (code != 0) {
      stderr.writeln('✖ $leaf failed (exit $code)');
      exit(code);
    }
  }
  stdout.writeln('✔ done');
}
