-- drop.sql — remove all Secret-Sauce app objects from the public schema.
-- Safe to run repeatedly. Does NOT touch auth.users accounts (only the
-- profile trigger). Use `db:create` afterwards to rebuild.

-- Trigger on auth.users that references our function.
drop trigger if exists on_auth_user_created on auth.users;

-- Tables (cascade clears dependent rows, FKs, indexes, policies).
drop table if exists
  recipe_suggestions,
  recipe_ratings,
  recipe_views,
  recipe_saves,
  recipe_likes,
  recipe_shares,
  recipe_tags,
  tags,
  steps,
  step_groups,
  ingredients,
  ingredient_groups,
  recipe_versions,
  recipes,
  profiles
cascade;

-- Functions.
drop function if exists handle_new_user() cascade;
drop function if exists bump_count(uuid, text, int) cascade;
drop function if exists on_like_change() cascade;
drop function if exists on_save_change() cascade;
drop function if exists on_view_insert() cascade;
drop function if exists on_rating_change() cascade;
drop function if exists on_version_insert() cascade;
drop function if exists recompute_recipe_rating(uuid) cascade;
drop function if exists touch_updated_at() cascade;
drop function if exists recipe_search_document(uuid) cascade;
drop function if exists recipe_search_tsv(uuid, text, text) cascade;
drop function if exists refresh_search_tsv(uuid[]) cascade;
drop function if exists on_recipe_search_change() cascade;
drop function if exists on_ingredients_search_change() cascade;
drop function if exists on_ingredient_groups_search_change() cascade;
drop function if exists on_recipe_tags_search_change() cascade;
drop function if exists on_tags_search_change() cascade;
drop function if exists can_read_recipe(uuid) cascade;
drop function if exists owns_recipe(uuid) cascade;
-- Discovery RPC signatures, oldest first: OPT-P9 added `p_offset`, and Postgres
-- keys drops by argument list, so both overloads stay listed.
drop function if exists recipes_trending(int) cascade;
drop function if exists recipes_trending(int, int) cascade;
drop function if exists recipes_popular(int) cascade;
drop function if exists recipes_popular(int, int) cascade;
drop function if exists recipes_search(text, int) cascade;
drop function if exists recipes_search(text, int, int) cascade;
-- The three Discover shelves and the rating prior they share (Phase 26).
drop function if exists recipes_quick(int, int) cascade;
drop function if exists recipes_projects(int, int) cascade;
drop function if exists recipes_most_forked(int, int) cascade;
-- `recipes_popular` and `recipes_quick` cross-join this one, but a quoted SQL
-- function body records no dependency, so `cascade` does not reach them —
-- they are dropped by name above, and both are recreated by the migrations.
drop function if exists site_rating_prior() cascade;
drop function if exists fork_recipe(uuid) cascade;
drop function if exists save_recipe(uuid, jsonb, jsonb, jsonb, text) cascade;
drop function if exists recipe_snapshot(uuid) cascade;
-- Chefs / leaderboard (Phase 18).
drop function if exists on_recipe_stats_change() cascade;
drop function if exists recompute_chef_stats(uuid) cascade;
drop function if exists recompute_all_chef_stats() cascade;
drop function if exists chef_score(bigint, bigint, bigint) cascade;
drop function if exists chef_tier_for(numeric) cascade;
drop function if exists chefs_leaderboard(int, int) cascade;
drop function if exists chefs_tier_counts() cascade;
drop function if exists chef_top_recipes(uuid, int) cascade;
-- seed_recipe signatures, oldest first. Each parameter-list change leaves the
-- previous overload behind, so every historical signature stays listed here.
drop function if exists seed_recipe(uuid, text, text, text, text, difficulty, int, int, int, text, jsonb, jsonb, int, int, int) cascade;
drop function if exists seed_recipe(uuid, text, text, text, text, difficulty, int, int, int, text, jsonb, jsonb, int, int, int, jsonb) cascade;
drop function if exists seed_recipe(uuid, text, text, text, text, difficulty, int, int, int, text, jsonb, jsonb, int, int, int, jsonb, recipe_visibility) cascade;
drop function if exists seed_taster_ids() cascade;
drop function if exists seed_chef_ids() cascade;
drop function if exists seed_ratings(uuid, jsonb) cascade;
-- seed_recipe_v2 signatures (supabase/seed_recipes.sql — GENERATED by
-- tool/recipes.dart). Both are `language plpgsql`, so their bodies are opaque to
-- the dependency tracker and `drop table ... cascade` above does NOT take them:
-- without these lines they survive a `db:drop` as functions over dropped tables
-- (B042). Same rule as seed_recipe: every historical signature stays listed,
-- oldest first, because Postgres keys drops by argument list.
drop function if exists seed_recipe_v2(uuid, text, text, text, text, difficulty, int, int, int, recipe_visibility, text, jsonb, jsonb, int, int, int, jsonb) cascade;
drop function if exists seed_recipe_v2_ratings(uuid, jsonb) cascade;

-- Enums.
drop type if exists difficulty cascade;
drop type if exists recipe_visibility cascade;
drop type if exists share_permission cascade;
drop type if exists suggestion_status cascade;
drop type if exists chef_tier cascade;
